// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: players_api/players.proto

package players_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayersService_GetAllTopics_FullMethodName           = "/players.service.v1.PlayersService/GetAllTopics"
	PlayersService_GetTenQuestionsByTopic_FullMethodName = "/players.service.v1.PlayersService/GetTenQuestionsByTopic"
	PlayersService_GetLeaderboardByTopics_FullMethodName = "/players.service.v1.PlayersService/GetLeaderboardByTopics"
	PlayersService_SetResultsByQuiz_FullMethodName       = "/players.service.v1.PlayersService/SetResultsByQuiz"
)

// PlayersServiceClient is the client API for PlayersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayersServiceClient interface {
	GetAllTopics(ctx context.Context, in *GetAllTopicsRequest, opts ...grpc.CallOption) (*GetAllTopicsResponse, error)
	GetTenQuestionsByTopic(ctx context.Context, in *GetTenQuestionsByTopicRequest, opts ...grpc.CallOption) (*GetTenQuestionsByTopicResponse, error)
	GetLeaderboardByTopics(ctx context.Context, in *GetLeaderboardByTopicsRequest, opts ...grpc.CallOption) (*GetLeaderboardByTopicsResponse, error)
	SetResultsByQuiz(ctx context.Context, in *SetResultsByQuizRequest, opts ...grpc.CallOption) (*SetResultsByQuizResponse, error)
}

type playersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayersServiceClient(cc grpc.ClientConnInterface) PlayersServiceClient {
	return &playersServiceClient{cc}
}

func (c *playersServiceClient) GetAllTopics(ctx context.Context, in *GetAllTopicsRequest, opts ...grpc.CallOption) (*GetAllTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllTopicsResponse)
	err := c.cc.Invoke(ctx, PlayersService_GetAllTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playersServiceClient) GetTenQuestionsByTopic(ctx context.Context, in *GetTenQuestionsByTopicRequest, opts ...grpc.CallOption) (*GetTenQuestionsByTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenQuestionsByTopicResponse)
	err := c.cc.Invoke(ctx, PlayersService_GetTenQuestionsByTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playersServiceClient) GetLeaderboardByTopics(ctx context.Context, in *GetLeaderboardByTopicsRequest, opts ...grpc.CallOption) (*GetLeaderboardByTopicsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLeaderboardByTopicsResponse)
	err := c.cc.Invoke(ctx, PlayersService_GetLeaderboardByTopics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playersServiceClient) SetResultsByQuiz(ctx context.Context, in *SetResultsByQuizRequest, opts ...grpc.CallOption) (*SetResultsByQuizResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResultsByQuizResponse)
	err := c.cc.Invoke(ctx, PlayersService_SetResultsByQuiz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlayersServiceServer is the server API for PlayersService service.
// All implementations must embed UnimplementedPlayersServiceServer
// for forward compatibility.
type PlayersServiceServer interface {
	GetAllTopics(context.Context, *GetAllTopicsRequest) (*GetAllTopicsResponse, error)
	GetTenQuestionsByTopic(context.Context, *GetTenQuestionsByTopicRequest) (*GetTenQuestionsByTopicResponse, error)
	GetLeaderboardByTopics(context.Context, *GetLeaderboardByTopicsRequest) (*GetLeaderboardByTopicsResponse, error)
	SetResultsByQuiz(context.Context, *SetResultsByQuizRequest) (*SetResultsByQuizResponse, error)
	mustEmbedUnimplementedPlayersServiceServer()
}

// UnimplementedPlayersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayersServiceServer struct{}

func (UnimplementedPlayersServiceServer) GetAllTopics(context.Context, *GetAllTopicsRequest) (*GetAllTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllTopics not implemented")
}
func (UnimplementedPlayersServiceServer) GetTenQuestionsByTopic(context.Context, *GetTenQuestionsByTopicRequest) (*GetTenQuestionsByTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenQuestionsByTopic not implemented")
}
func (UnimplementedPlayersServiceServer) GetLeaderboardByTopics(context.Context, *GetLeaderboardByTopicsRequest) (*GetLeaderboardByTopicsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboardByTopics not implemented")
}
func (UnimplementedPlayersServiceServer) SetResultsByQuiz(context.Context, *SetResultsByQuizRequest) (*SetResultsByQuizResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetResultsByQuiz not implemented")
}
func (UnimplementedPlayersServiceServer) mustEmbedUnimplementedPlayersServiceServer() {}
func (UnimplementedPlayersServiceServer) testEmbeddedByValue()                        {}

// UnsafePlayersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayersServiceServer will
// result in compilation errors.
type UnsafePlayersServiceServer interface {
	mustEmbedUnimplementedPlayersServiceServer()
}

func RegisterPlayersServiceServer(s grpc.ServiceRegistrar, srv PlayersServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayersService_ServiceDesc, srv)
}

func _PlayersService_GetAllTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayersServiceServer).GetAllTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayersService_GetAllTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayersServiceServer).GetAllTopics(ctx, req.(*GetAllTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayersService_GetTenQuestionsByTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenQuestionsByTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayersServiceServer).GetTenQuestionsByTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayersService_GetTenQuestionsByTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayersServiceServer).GetTenQuestionsByTopic(ctx, req.(*GetTenQuestionsByTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayersService_GetLeaderboardByTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardByTopicsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayersServiceServer).GetLeaderboardByTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayersService_GetLeaderboardByTopics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayersServiceServer).GetLeaderboardByTopics(ctx, req.(*GetLeaderboardByTopicsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayersService_SetResultsByQuiz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetResultsByQuizRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayersServiceServer).SetResultsByQuiz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayersService_SetResultsByQuiz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayersServiceServer).SetResultsByQuiz(ctx, req.(*SetResultsByQuizRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlayersService_ServiceDesc is the grpc.ServiceDesc for PlayersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "players.service.v1.PlayersService",
	HandlerType: (*PlayersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTopics",
			Handler:    _PlayersService_GetAllTopics_Handler,
		},
		{
			MethodName: "GetTenQuestionsByTopic",
			Handler:    _PlayersService_GetTenQuestionsByTopic_Handler,
		},
		{
			MethodName: "GetLeaderboardByTopics",
			Handler:    _PlayersService_GetLeaderboardByTopics_Handler,
		},
		{
			MethodName: "SetResultsByQuiz",
			Handler:    _PlayersService_SetResultsByQuiz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "players_api/players.proto",
}
