// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: admins_api/admins.proto

package admins_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminsService_SetUserData_FullMethodName = "/admins.service.v1.AdminsService/SetUserData"
)

// AdminsServiceClient is the client API for AdminsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminsServiceClient interface {
	SetUserData(ctx context.Context, in *SetUserDataRequest, opts ...grpc.CallOption) (*SetUserDataResponse, error)
}

type adminsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminsServiceClient(cc grpc.ClientConnInterface) AdminsServiceClient {
	return &adminsServiceClient{cc}
}

func (c *adminsServiceClient) SetUserData(ctx context.Context, in *SetUserDataRequest, opts ...grpc.CallOption) (*SetUserDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserDataResponse)
	err := c.cc.Invoke(ctx, AdminsService_SetUserData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminsServiceServer is the server API for AdminsService service.
// All implementations must embed UnimplementedAdminsServiceServer
// for forward compatibility.
type AdminsServiceServer interface {
	SetUserData(context.Context, *SetUserDataRequest) (*SetUserDataResponse, error)
	mustEmbedUnimplementedAdminsServiceServer()
}

// UnimplementedAdminsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminsServiceServer struct{}

func (UnimplementedAdminsServiceServer) SetUserData(context.Context, *SetUserDataRequest) (*SetUserDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserData not implemented")
}
func (UnimplementedAdminsServiceServer) mustEmbedUnimplementedAdminsServiceServer() {}
func (UnimplementedAdminsServiceServer) testEmbeddedByValue()                       {}

// UnsafeAdminsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminsServiceServer will
// result in compilation errors.
type UnsafeAdminsServiceServer interface {
	mustEmbedUnimplementedAdminsServiceServer()
}

func RegisterAdminsServiceServer(s grpc.ServiceRegistrar, srv AdminsServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminsService_ServiceDesc, srv)
}

func _AdminsService_SetUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminsServiceServer).SetUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminsService_SetUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminsServiceServer).SetUserData(ctx, req.(*SetUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminsService_ServiceDesc is the grpc.ServiceDesc for AdminsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admins.service.v1.AdminsService",
	HandlerType: (*AdminsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUserData",
			Handler:    _AdminsService_SetUserData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admins_api/admins.proto",
}
