// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: admins_api/admins.proto

package admins_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserDataRequest) Reset() {
	*x = SetUserDataRequest{}
	mi := &file_admins_api_admins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDataRequest) ProtoMessage() {}

func (x *SetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admins_api_admins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDataRequest.ProtoReflect.Descriptor instead.
func (*SetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_admins_api_admins_proto_rawDescGZIP(), []int{0}
}

func (x *SetUserDataRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

func (x *SetUserDataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetUserDataRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type SetUserDataResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserDataResponce) Reset() {
	*x = SetUserDataResponce{}
	mi := &file_admins_api_admins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserDataResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserDataResponce) ProtoMessage() {}

func (x *SetUserDataResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admins_api_admins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserDataResponce.ProtoReflect.Descriptor instead.
func (*SetUserDataResponce) Descriptor() ([]byte, []int) {
	return file_admins_api_admins_proto_rawDescGZIP(), []int{1}
}

func (x *SetUserDataResponce) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    int64                  `protobuf:"varint,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsRequest) Reset() {
	*x = GetUserPermissionsRequest{}
	mi := &file_admins_api_admins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsRequest) ProtoMessage() {}

func (x *GetUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admins_api_admins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_admins_api_admins_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPermissionsRequest) GetTelegramId() int64 {
	if x != nil {
		return x.TelegramId
	}
	return 0
}

type GetUserPermissionsResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []string               `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPermissionsResponce) Reset() {
	*x = GetUserPermissionsResponce{}
	mi := &file_admins_api_admins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPermissionsResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPermissionsResponce) ProtoMessage() {}

func (x *GetUserPermissionsResponce) ProtoReflect() protoreflect.Message {
	mi := &file_admins_api_admins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPermissionsResponce.ProtoReflect.Descriptor instead.
func (*GetUserPermissionsResponce) Descriptor() ([]byte, []int) {
	return file_admins_api_admins_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPermissionsResponce) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_admins_api_admins_proto protoreflect.FileDescriptor

const file_admins_api_admins_proto_rawDesc = "" +
	"\n" +
	"\x17admins_api/admins.proto\x12\x11admins.service.v1\x1a\x18models/admin_model.proto\x1a\x1cgoogle/api/annotations.proto\"e\n" +
	"\x12SetUserDataRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"A\n" +
	"\x13SetUserDataResponce\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x16.admins.models.v1.UserR\x04user\"<\n" +
	"\x19GetUserPermissionsRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\x03R\n" +
	"telegramId\">\n" +
	"\x1aGetUserPermissionsResponce\x12 \n" +
	"\vpermissions\x18\x01 \x03(\tR\vpermissions2\xa8\x02\n" +
	"\rAdminsService\x12y\n" +
	"\vSetUserData\x12%.admins.service.v1.SetUserDataRequest\x1a&.admins.service.v1.SetUserDataResponce\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/users/start\x12\x9b\x01\n" +
	"\x12GetUserPermissions\x12,.admins.service.v1.GetUserPermissionsRequest\x1a-.admins.service.v1.GetUserPermissionsResponce\"(\x82\xd3\xe4\x93\x02\"\x12 /api/users/{user_id}/permissionsBJZHgithub.com/Vladislav-Evg-Sid/quizbot/server-admin/internal/pb/admins_apib\x06proto3"

var (
	file_admins_api_admins_proto_rawDescOnce sync.Once
	file_admins_api_admins_proto_rawDescData []byte
)

func file_admins_api_admins_proto_rawDescGZIP() []byte {
	file_admins_api_admins_proto_rawDescOnce.Do(func() {
		file_admins_api_admins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admins_api_admins_proto_rawDesc), len(file_admins_api_admins_proto_rawDesc)))
	})
	return file_admins_api_admins_proto_rawDescData
}

var file_admins_api_admins_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admins_api_admins_proto_goTypes = []any{
	(*SetUserDataRequest)(nil),         // 0: admins.service.v1.SetUserDataRequest
	(*SetUserDataResponce)(nil),        // 1: admins.service.v1.SetUserDataResponce
	(*GetUserPermissionsRequest)(nil),  // 2: admins.service.v1.GetUserPermissionsRequest
	(*GetUserPermissionsResponce)(nil), // 3: admins.service.v1.GetUserPermissionsResponce
	(*User)(nil),                       // 4: admins.models.v1.User
}
var file_admins_api_admins_proto_depIdxs = []int32{
	4, // 0: admins.service.v1.SetUserDataResponce.user:type_name -> admins.models.v1.User
	0, // 1: admins.service.v1.AdminsService.SetUserData:input_type -> admins.service.v1.SetUserDataRequest
	2, // 2: admins.service.v1.AdminsService.GetUserPermissions:input_type -> admins.service.v1.GetUserPermissionsRequest
	1, // 3: admins.service.v1.AdminsService.SetUserData:output_type -> admins.service.v1.SetUserDataResponce
	3, // 4: admins.service.v1.AdminsService.GetUserPermissions:output_type -> admins.service.v1.GetUserPermissionsResponce
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_admins_api_admins_proto_init() }
func file_admins_api_admins_proto_init() {
	if File_admins_api_admins_proto != nil {
		return
	}
	file_models_admin_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admins_api_admins_proto_rawDesc), len(file_admins_api_admins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admins_api_admins_proto_goTypes,
		DependencyIndexes: file_admins_api_admins_proto_depIdxs,
		MessageInfos:      file_admins_api_admins_proto_msgTypes,
	}.Build()
	File_admins_api_admins_proto = out.File
	file_admins_api_admins_proto_goTypes = nil
	file_admins_api_admins_proto_depIdxs = nil
}
