// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: players_api/players.proto

package players_api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTopicsRequest) Reset() {
	*x = GetAllTopicsRequest{}
	mi := &file_players_api_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTopicsRequest) ProtoMessage() {}

func (x *GetAllTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetAllTopicsRequest) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{0}
}

type GetAllTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTopicsResponse) Reset() {
	*x = GetAllTopicsResponse{}
	mi := &file_players_api_players_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTopicsResponse) ProtoMessage() {}

func (x *GetAllTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetAllTopicsResponse) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllTopicsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *GetAllTopicsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type GetTenQuestionsByTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenQuestionsByTopicRequest) Reset() {
	*x = GetTenQuestionsByTopicRequest{}
	mi := &file_players_api_players_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenQuestionsByTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenQuestionsByTopicRequest) ProtoMessage() {}

func (x *GetTenQuestionsByTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenQuestionsByTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTenQuestionsByTopicRequest) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenQuestionsByTopicRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type GetTenQuestionsByTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Questions     []*Question            `protobuf:"bytes,2,rep,name=questions,proto3" json:"questions,omitempty"`
	TopicId       int32                  `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenQuestionsByTopicResponse) Reset() {
	*x = GetTenQuestionsByTopicResponse{}
	mi := &file_players_api_players_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenQuestionsByTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenQuestionsByTopicResponse) ProtoMessage() {}

func (x *GetTenQuestionsByTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenQuestionsByTopicResponse.ProtoReflect.Descriptor instead.
func (*GetTenQuestionsByTopicResponse) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{3}
}

func (x *GetTenQuestionsByTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTenQuestionsByTopicResponse) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetTenQuestionsByTopicResponse) GetTopicId() int32 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetTenQuestionsByTopicResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_players_api_players_proto protoreflect.FileDescriptor

const file_players_api_players_proto_rawDesc = "" +
	"\n" +
	"\x19players_api/players.proto\x12\x12players.service.v1\x1a\x19models/player_model.proto\x1a\x1cgoogle/api/annotations.proto\"\x15\n" +
	"\x13GetAllTopicsRequest\"\x88\x01\n" +
	"\x14GetAllTopicsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\x06topics\x18\x02 \x03(\v2\x19.players.service.v1.TopicR\x06topics\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\">\n" +
	"\x1dGetTenQuestionsByTopicRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"\xb6\x01\n" +
	"\x1eGetTenQuestionsByTopicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\tquestions\x18\x02 \x03(\v2\x1c.players.service.v1.QuestionR\tquestions\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\x05R\atopicId\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xbf\x02\n" +
	"\x0ePlayersService\x12|\n" +
	"\fGetAllTopics\x12'.players.service.v1.GetAllTopicsRequest\x1a(.players.service.v1.GetAllTopicsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/users/topics\x12\xae\x01\n" +
	"\x16GetTenQuestionsByTopic\x121.players.service.v1.GetTenQuestionsByTopicRequest\x1a2.players.service.v1.GetTenQuestionsByTopicResponse\"-\x82\xd3\xe4\x93\x02'\x12%/api/player/tenquestions/{topic_name}BLZJgithub.com/Vladislav-Evg-Sid/quizbot/server-player/internal/pb/players_apib\x06proto3"

var (
	file_players_api_players_proto_rawDescOnce sync.Once
	file_players_api_players_proto_rawDescData []byte
)

func file_players_api_players_proto_rawDescGZIP() []byte {
	file_players_api_players_proto_rawDescOnce.Do(func() {
		file_players_api_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_players_api_players_proto_rawDesc), len(file_players_api_players_proto_rawDesc)))
	})
	return file_players_api_players_proto_rawDescData
}

var file_players_api_players_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_players_api_players_proto_goTypes = []any{
	(*GetAllTopicsRequest)(nil),            // 0: players.service.v1.GetAllTopicsRequest
	(*GetAllTopicsResponse)(nil),           // 1: players.service.v1.GetAllTopicsResponse
	(*GetTenQuestionsByTopicRequest)(nil),  // 2: players.service.v1.GetTenQuestionsByTopicRequest
	(*GetTenQuestionsByTopicResponse)(nil), // 3: players.service.v1.GetTenQuestionsByTopicResponse
	(*Topic)(nil),                          // 4: players.service.v1.Topic
	(*Question)(nil),                       // 5: players.service.v1.Question
}
var file_players_api_players_proto_depIdxs = []int32{
	4, // 0: players.service.v1.GetAllTopicsResponse.topics:type_name -> players.service.v1.Topic
	5, // 1: players.service.v1.GetTenQuestionsByTopicResponse.questions:type_name -> players.service.v1.Question
	0, // 2: players.service.v1.PlayersService.GetAllTopics:input_type -> players.service.v1.GetAllTopicsRequest
	2, // 3: players.service.v1.PlayersService.GetTenQuestionsByTopic:input_type -> players.service.v1.GetTenQuestionsByTopicRequest
	1, // 4: players.service.v1.PlayersService.GetAllTopics:output_type -> players.service.v1.GetAllTopicsResponse
	3, // 5: players.service.v1.PlayersService.GetTenQuestionsByTopic:output_type -> players.service.v1.GetTenQuestionsByTopicResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_players_api_players_proto_init() }
func file_players_api_players_proto_init() {
	if File_players_api_players_proto != nil {
		return
	}
	file_models_player_model_proto_init()
	file_players_api_players_proto_msgTypes[1].OneofWrappers = []any{}
	file_players_api_players_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_players_api_players_proto_rawDesc), len(file_players_api_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_players_api_players_proto_goTypes,
		DependencyIndexes: file_players_api_players_proto_depIdxs,
		MessageInfos:      file_players_api_players_proto_msgTypes,
	}.Build()
	File_players_api_players_proto = out.File
	file_players_api_players_proto_goTypes = nil
	file_players_api_players_proto_depIdxs = nil
}
