// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: players_api/players.proto

package players_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTopicsRequest) Reset() {
	*x = GetAllTopicsRequest{}
	mi := &file_players_api_players_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTopicsRequest) ProtoMessage() {}

func (x *GetAllTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetAllTopicsRequest) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{0}
}

type GetAllTopicsResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllTopicsResponce) Reset() {
	*x = GetAllTopicsResponce{}
	mi := &file_players_api_players_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllTopicsResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTopicsResponce) ProtoMessage() {}

func (x *GetAllTopicsResponce) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTopicsResponce.ProtoReflect.Descriptor instead.
func (*GetAllTopicsResponce) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllTopicsResponce) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetTenQuestionsByTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenQuestionsByTopicRequest) Reset() {
	*x = GetTenQuestionsByTopicRequest{}
	mi := &file_players_api_players_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenQuestionsByTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenQuestionsByTopicRequest) ProtoMessage() {}

func (x *GetTenQuestionsByTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenQuestionsByTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTenQuestionsByTopicRequest) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenQuestionsByTopicRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type GetTenQuestionsByTopicResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Questions     []*Question            `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenQuestionsByTopicResponce) Reset() {
	*x = GetTenQuestionsByTopicResponce{}
	mi := &file_players_api_players_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenQuestionsByTopicResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenQuestionsByTopicResponce) ProtoMessage() {}

func (x *GetTenQuestionsByTopicResponce) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenQuestionsByTopicResponce.ProtoReflect.Descriptor instead.
func (*GetTenQuestionsByTopicResponce) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{3}
}

func (x *GetTenQuestionsByTopicResponce) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetTenQuestionsByTopicResponce) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type SetResultsByQuizRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TgId          int64                  `protobuf:"varint,1,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	ThemaId       int32                  `protobuf:"varint,2,opt,name=thema_id,json=themaId,proto3" json:"thema_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Time          int32                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResultsByQuizRequest) Reset() {
	*x = SetResultsByQuizRequest{}
	mi := &file_players_api_players_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResultsByQuizRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResultsByQuizRequest) ProtoMessage() {}

func (x *SetResultsByQuizRequest) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResultsByQuizRequest.ProtoReflect.Descriptor instead.
func (*SetResultsByQuizRequest) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{4}
}

func (x *SetResultsByQuizRequest) GetTgId() int64 {
	if x != nil {
		return x.TgId
	}
	return 0
}

func (x *SetResultsByQuizRequest) GetThemaId() int32 {
	if x != nil {
		return x.ThemaId
	}
	return 0
}

func (x *SetResultsByQuizRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SetResultsByQuizRequest) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type SetResultsByQuizResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResultsByQuizResponce) Reset() {
	*x = SetResultsByQuizResponce{}
	mi := &file_players_api_players_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResultsByQuizResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResultsByQuizResponce) ProtoMessage() {}

func (x *SetResultsByQuizResponce) ProtoReflect() protoreflect.Message {
	mi := &file_players_api_players_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResultsByQuizResponce.ProtoReflect.Descriptor instead.
func (*SetResultsByQuizResponce) Descriptor() ([]byte, []int) {
	return file_players_api_players_proto_rawDescGZIP(), []int{5}
}

var File_players_api_players_proto protoreflect.FileDescriptor

const file_players_api_players_proto_rawDesc = "" +
	"\n" +
	"\x19players_api/players.proto\x12\x12players.service.v1\x1a\x19models/player_model.proto\x1a\x1cgoogle/api/annotations.proto\"\x15\n" +
	"\x13GetAllTopicsRequest\"H\n" +
	"\x14GetAllTopicsResponce\x120\n" +
	"\x06topics\x18\x01 \x03(\v2\x18.players.models.v1.TopicR\x06topics\">\n" +
	"\x1dGetTenQuestionsByTopicRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"v\n" +
	"\x1eGetTenQuestionsByTopicResponce\x129\n" +
	"\tquestions\x18\x01 \x03(\v2\x1b.players.models.v1.QuestionR\tquestions\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\"s\n" +
	"\x17SetResultsByQuizRequest\x12\x13\n" +
	"\x05tg_id\x18\x01 \x01(\x03R\x04tgId\x12\x19\n" +
	"\bthema_id\x18\x02 \x01(\x05R\athemaId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x05R\x04time\"\x1a\n" +
	"\x18SetResultsByQuizResponce2\xd0\x03\n" +
	"\x0ePlayersService\x12|\n" +
	"\fGetAllTopics\x12'.players.service.v1.GetAllTopicsRequest\x1a(.players.service.v1.GetAllTopicsResponce\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/users/topics\x12\xae\x01\n" +
	"\x16GetTenQuestionsByTopic\x121.players.service.v1.GetTenQuestionsByTopicRequest\x1a2.players.service.v1.GetTenQuestionsByTopicResponce\"-\x82\xd3\xe4\x93\x02'\x12%/api/player/tenquestions/{topic_name}\x12\x8e\x01\n" +
	"\x10SetResultsByQuiz\x12+.players.service.v1.SetResultsByQuizRequest\x1a,.players.service.v1.SetResultsByQuizResponce\"\x1f\x82\xd3\xe4\x93\x02\x19\x1a\x17/api/player/quiz/finishBLZJgithub.com/Vladislav-Evg-Sid/quizbot/server-player/internal/pb/players_apib\x06proto3"

var (
	file_players_api_players_proto_rawDescOnce sync.Once
	file_players_api_players_proto_rawDescData []byte
)

func file_players_api_players_proto_rawDescGZIP() []byte {
	file_players_api_players_proto_rawDescOnce.Do(func() {
		file_players_api_players_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_players_api_players_proto_rawDesc), len(file_players_api_players_proto_rawDesc)))
	})
	return file_players_api_players_proto_rawDescData
}

var file_players_api_players_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_players_api_players_proto_goTypes = []any{
	(*GetAllTopicsRequest)(nil),            // 0: players.service.v1.GetAllTopicsRequest
	(*GetAllTopicsResponce)(nil),           // 1: players.service.v1.GetAllTopicsResponce
	(*GetTenQuestionsByTopicRequest)(nil),  // 2: players.service.v1.GetTenQuestionsByTopicRequest
	(*GetTenQuestionsByTopicResponce)(nil), // 3: players.service.v1.GetTenQuestionsByTopicResponce
	(*SetResultsByQuizRequest)(nil),        // 4: players.service.v1.SetResultsByQuizRequest
	(*SetResultsByQuizResponce)(nil),       // 5: players.service.v1.SetResultsByQuizResponce
	(*Topic)(nil),                          // 6: players.models.v1.Topic
	(*Question)(nil),                       // 7: players.models.v1.Question
}
var file_players_api_players_proto_depIdxs = []int32{
	6, // 0: players.service.v1.GetAllTopicsResponce.topics:type_name -> players.models.v1.Topic
	7, // 1: players.service.v1.GetTenQuestionsByTopicResponce.questions:type_name -> players.models.v1.Question
	0, // 2: players.service.v1.PlayersService.GetAllTopics:input_type -> players.service.v1.GetAllTopicsRequest
	2, // 3: players.service.v1.PlayersService.GetTenQuestionsByTopic:input_type -> players.service.v1.GetTenQuestionsByTopicRequest
	4, // 4: players.service.v1.PlayersService.SetResultsByQuiz:input_type -> players.service.v1.SetResultsByQuizRequest
	1, // 5: players.service.v1.PlayersService.GetAllTopics:output_type -> players.service.v1.GetAllTopicsResponce
	3, // 6: players.service.v1.PlayersService.GetTenQuestionsByTopic:output_type -> players.service.v1.GetTenQuestionsByTopicResponce
	5, // 7: players.service.v1.PlayersService.SetResultsByQuiz:output_type -> players.service.v1.SetResultsByQuizResponce
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_players_api_players_proto_init() }
func file_players_api_players_proto_init() {
	if File_players_api_players_proto != nil {
		return
	}
	file_models_player_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_players_api_players_proto_rawDesc), len(file_players_api_players_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_players_api_players_proto_goTypes,
		DependencyIndexes: file_players_api_players_proto_depIdxs,
		MessageInfos:      file_players_api_players_proto_msgTypes,
	}.Build()
	File_players_api_players_proto = out.File
	file_players_api_players_proto_goTypes = nil
	file_players_api_players_proto_depIdxs = nil
}
