// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/player_model.proto

package players_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_models_player_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_models_player_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_models_player_model_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Question struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text               string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Options            []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	CorrectAnswerIndex int64                  `protobuf:"varint,4,opt,name=correct_answer_index,json=correctAnswerIndex,proto3" json:"correct_answer_index,omitempty"`
	Explanation        string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_models_player_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_models_player_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_models_player_model_proto_rawDescGZIP(), []int{1}
}

func (x *Question) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Question) GetCorrectAnswerIndex() int64 {
	if x != nil {
		return x.CorrectAnswerIndex
	}
	return 0
}

func (x *Question) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_models_player_model_proto protoreflect.FileDescriptor

const file_models_player_model_proto_rawDesc = "" +
	"\n" +
	"\x19models/player_model.proto\x12\x11players.models.v1\"-\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x9c\x01\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x120\n" +
	"\x14correct_answer_index\x18\x04 \x01(\x03R\x12correctAnswerIndex\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanationBLZJgithub.com/Vladislav-Evg-Sid/quizbot/server-player/internal/pb/players_apib\x06proto3"

var (
	file_models_player_model_proto_rawDescOnce sync.Once
	file_models_player_model_proto_rawDescData []byte
)

func file_models_player_model_proto_rawDescGZIP() []byte {
	file_models_player_model_proto_rawDescOnce.Do(func() {
		file_models_player_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_player_model_proto_rawDesc), len(file_models_player_model_proto_rawDesc)))
	})
	return file_models_player_model_proto_rawDescData
}

var file_models_player_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_models_player_model_proto_goTypes = []any{
	(*Topic)(nil),    // 0: players.models.v1.Topic
	(*Question)(nil), // 1: players.models.v1.Question
}
var file_models_player_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_player_model_proto_init() }
func file_models_player_model_proto_init() {
	if File_models_player_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_player_model_proto_rawDesc), len(file_models_player_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_player_model_proto_goTypes,
		DependencyIndexes: file_models_player_model_proto_depIdxs,
		MessageInfos:      file_models_player_model_proto_msgTypes,
	}.Build()
	File_models_player_model_proto = out.File
	file_models_player_model_proto_goTypes = nil
	file_models_player_model_proto_depIdxs = nil
}
