// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/playerService/player_service.go

package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Vladislav-Evg-Sid/quizbot/server-player/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockQuizResultProducer is a mock of QuizResultProducer interface.
type MockQuizResultProducer struct {
	ctrl     *gomock.Controller
	recorder *MockQuizResultProducerMockRecorder
}

// MockQuizResultProducerMockRecorder is the mock recorder for MockQuizResultProducer.
type MockQuizResultProducerMockRecorder struct {
	mock *MockQuizResultProducer
}

func NewMockQuizResultProducer(ctrl *gomock.Controller) *MockQuizResultProducer {
	mock := &MockQuizResultProducer{ctrl: ctrl}
	mock.recorder = &MockQuizResultProducerMockRecorder{mock}
	return mock
}

func (m *MockQuizResultProducer) EXPECT() *MockQuizResultProducerMockRecorder {
	return m.recorder
}

func (m *MockQuizResultProducer) SendQuizResult(ctx context.Context, result *models.QuizRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendQuizResult", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockQuizResultProducerMockRecorder) SendQuizResult(ctx, result interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendQuizResult", reflect.TypeOf((*MockQuizResultProducer)(nil).SendQuizResult), ctx, result)
}
