// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/playerService/player_service.go

package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Vladislav-Evg-Sid/quizbot/server-player/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockPlayerStorage is a mock of PlayerStorage interface.
type MockPlayerStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPlayerStorageMockRecorder
}

// MockPlayerStorageMockRecorder is the mock recorder for MockPlayerStorage.
type MockPlayerStorageMockRecorder struct {
	mock *MockPlayerStorage
}

func NewMockPlayerStorage(ctrl *gomock.Controller) *MockPlayerStorage {
	mock := &MockPlayerStorage{ctrl: ctrl}
	mock.recorder = &MockPlayerStorageMockRecorder{mock}
	return mock
}

func (m *MockPlayerStorage) EXPECT() *MockPlayerStorageMockRecorder {
	return m.recorder
}

func (m *MockPlayerStorage) GetAllTopics(ctx context.Context) ([]*models.ActiveTopics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTopics", ctx)
	ret0, _ := ret[0].([]*models.ActiveTopics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlayerStorageMockRecorder) GetAllTopics(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTopics", reflect.TypeOf((*MockPlayerStorage)(nil).GetAllTopics), ctx)
}

func (m *MockPlayerStorage) GetTopicIdByName(ctx context.Context, topic_name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopicIdByName", ctx, topic_name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlayerStorageMockRecorder) GetTopicIdByName(ctx, topic_name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopicIdByName", reflect.TypeOf((*MockPlayerStorage)(nil).GetTopicIdByName), ctx, topic_name)
}

func (m *MockPlayerStorage) GetTenQuestionsByTopicID(ctx context.Context, topic_id int) ([]*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenQuestionsByTopicID", ctx, topic_id)
	ret0, _ := ret[0].([]*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockPlayerStorageMockRecorder) GetTenQuestionsByTopicID(ctx, topic_id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenQuestionsByTopicID", reflect.TypeOf((*MockPlayerStorage)(nil).GetTenQuestionsByTopicID), ctx, topic_id)
}
